### ISSUE TITLE
unable to turn off, until max speed

### ISSUE THREAD

**Issue by dexop** [EFeru/hoverboard-firmware-hack-FOC#313]
### Variant

ADC

### Control type

FOC

### Control mode

Torque

### Description

hello, thanks for all your work on this project.
i have problems turning off the main board.
dual mode, left side ADC, right IBUS.

everithing is working just fine, adc side, calibration, ibus side also.
the problem occurs when i try to shut down main board on button. it doesn't turn off.
but, when i push throtle (adc or ibus) to the max, then button react, and main board shuts down.

any ideas what to check?

**Comment by Candas1** [comment]
Hi,

What battery are you using?

**Comment by dexop** [comment]
standard battery  from hover board. 36v  4400mah

**Comment by Candas1** [comment]
How is your board looking like ?
Have you checking in the [wiki](https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki/Firmware-Compatibility) if it's a standard one ?

**Comment by Candas1** [comment]
What I don't understand is the button works when you are at max speed ? or the board turns off at max speed ?

**Comment by dexop** [comment]
button works only at max speed given by ibus or adc.

**Comment by Candas1** [comment]
Well then I don't know what this could come from.
If you are able to enter auto-calibration, this proves the button works and is mapped the right MCU pin, so turning off should work as well.

The reason I asked those question is because:
* some boards have the button mapped to a different pin, you would still be able to turn the board on, but you wouldn't be able to enter autocalibration or poweroff
* if the battery voltage is too low, because of the voltage divider between the button and the mcu, the voltage could be too low to pick up, but it would also impact autocalibration and poweroff 
* if the tip127 mosfet is shorted, the board would be always ON and you wouldn't be able to poweroff at all, but it doesn't seem to be your case

**Comment by mrendu43** [comment]
Hello.. 
Have you menaget to solve this problem, i  have the same with mine board using usart3.
I can power on, and enter calibration but it wont power off.

**Comment by Candas1** [comment]
> Hello.. Have you menaget to solve this problem, i have the same with mine board using usart3. I can power on, and enter calibration but it wont power off.

Have you checked what I suggested ?

**Comment by lsls5921** [comment]
Is there any way to use the hover board to control the DC brush motor

**Comment by Candas1** [comment]
> Is there any way to use the hover board to control the DC brush motor

Your questions is not relevant in this issue.
and the answer is no...

**Comment by hainanlin** [comment]
Is there any way to use the hover board to control the DC brush motor





---Original---
From: ***@***.***&gt;
Date: Sat, Jul 16, 2022 21:41 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [EFeru/hoverboard-firmware-hack-FOC] unable to turn off, untilmax speed (Issue #313)




 
Is there any way to use the hover board to control the DC brush motor

**Comment by Candas1** [comment]
The anwer is still no.... not with this firmware
But if you want you can code it

**Comment by hainanlin** [comment]
Thank you.



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 13, 2022 14:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [EFeru/hoverboard-firmware-hack-FOC] unable to turn off, untilmax speed (Issue #313)




 
The anwer is still no.... not with this firmware
 But if you want you can code it
